name: Test Workflow

on:
  push:
    branches: [ dev_firmware ]
  pull_request:
    branches: [ master, dev, dev_firmware]
  workflow_dispatch:  # allows manual execution

jobs:

  # Generates Matrix
  generate-matrix:
    name:

    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Generates JSON file with test program
      - name: Create JSON file
        run: python3 .github/workflows/deployJSON.py --source firmware/tests/devices/
      # Echo the JSON file
      - name: Resulting JSON file for matrix generation
        run: echo "$(cat .github/workflows/test-list.json)"
      # Set the matrix output from the JSON (manipulated to remove spaces and replace \n -> %0A, " -> \")
      - id: set-matrix
        name: Set matrix output from the JSON file
        run: echo "::set-output name=matrix::$( echo "$(cat .github/workflows/test-list.json)" | sed ':a;N;$!ba;s/\n/%0A/g' )"

  # Job for executing all test files
  run-tests:
    name: run-tests
    needs: generate-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}


    env:
      MAKE_TARGET: ${{ matrix.name }}
      TEST_FILE: ${{ matrix.test_name }}
      TEST_PATH: ${{ matrix.path }}

    steps:
      - uses: actions/checkout@v2
      # Install required libs
      - name: Install CMocka
        run: sudo apt-get install libcmocka0 libcmocka-dev
      - name: Signal make target
        run: echo "Generating make file for $MAKE_TARGET"
      - name: Generate Test File
        # '-lcmocka' must be the last compilation flag
        run: cd firmware/tests/devices && make $MAKE_TARGET
      - name: Signal running test
        run: echo "Running $TEST_FILE"
      - name: Run test
        run: $TEST_PATH
